### Créer un item
POST http://localhost:4000/items
Content-Type: application/json

{
  "title": "câble usb",
  "quantity": 10,
  "color": "#000000"
}

###

### Récupérer tous les utilisateurs (si tu fais une route GET plus tard)
GET http://localhost:4000/items

### PATCH un item existant (remplace `YOUR_ITEM_ID` par un vrai ID)
PATCH http://localhost:4000/items/2
Content-Type: application/json

{
  "title" : "fraise",
  "quantity": 7,
  "color": "#51d821"
}

### DELETE un item existant (remplace `YOUR_ITEM_ID` par un vrai ID)
DELETE http://localhost:4000/items/1
Content-Type: application/json